---
title: "Lecture 6: Exercises"
date: October 19th, 2017
output: 
  html_notebook:
    toc: true
    toc_float: true
---

# Exercise 1: Hypothesis testing

Similarly to dataset `mtcars`, the dataset `mpg` from `ggplot` package 
includes data on automobiles. However, `mpg` includes data for newer
cars from year 1999 and 2008. The variables measured for each car is slighly 
different. Here we are interested in the variable, `hwy`, the highway miles per 
gallon.

## Part 1: One-sample test

a. Subset the `mpg` dataset to inlude only cars from  year 2008.
b. Test whether cars from 2008 have mean the highway miles per gallon, `hwy`, 
equal to 30 mpg.
c. Test whether cars from 2008 with 4 cylinders have mean `hwy` equal to 30 mpg.

## Part 2: Two-sample test

a. Test if the mean `hwy` for automatic is **less than** that for manual cars
**in 2008**. Generate a boxplot with jittered points
for `hwy` for each transmission group.
b. Test if the mean `hwy` for cars from 1999 and is greater than that for
cars from 2008. Generate a boxplot with jittered points
for `hwy` for each year group.

```{r}
library(ggplot2)
library(dplyr)

mpg
# We create a new culumn with manual/automatic data only
mpg <- mpg %>% 
  mutate(transmission =factor(gsub("\\((.*)", "", trans)))
mpg
```


# Exercise 2: Linear Regression

## Part 1

The data in the following URL "http://www-bcf.usc.edu/~gareth/ISL/Income1.csv"
includes observation on income levels (in tens of thousands of dollars)
and years of education. *The data is not real and was actually simulated*.

a. Read the data into R.

b. Generate a ggplot with a fitted line.

c. Fit a linear model with education as input variable and income as response 
variable. Then, print the model summary

d. Print out just the model coefficients.

d. Print out the predicted values of income for the observations
included in the dataset.

e. Predict the income for new observations, for people with 
16.00, 12.52, 15.55, 21.09, and 18.36 years of education.


## Part 2

a. Now download data from "http://www-bcf.usc.edu/~gareth/ISL/Income2.csv"
which include the same observations but also records data on "senority".

b. Fit a new model including a new variable and print the model summary.

c. Print the predicted values of income for the existing observations.

d. Predict the income levels for new observations with years of education
equal to 16.00, 12.52, 15.55, 21.09, 18.36 and seniority to
123.74, 83.63,  90.94, 178.96, 125.17.

